Fixed manage.extract_ddl for py3
It opens file in binary mode and then writes text to it.
While this works in python2, with py3 it causes an error:

$ python manage.py extract_ddl /
<...>
  File "manage.py", line 69, in extract_ddl
    f.write('-- This file is generated using "python manage.py extract_ddl"'
TypeError: <flask_script.commands.Command object at 0x7f55d2ebb470>: a bytes-like object is required, not 'str'